# .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main server.go"
  bin = "./tmp/main"
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = ["server.go"]  # Explicitly include server.go
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true
  poll = true  # Enable polling for file changes
  poll_interval = 1000  # Poll every 1000ms

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
